<start> ::= <S> ;
<S> ::= <F> ';' <S> | <C> ;
<F> ::= 'fun' 'id' <A> '->' <C> ;
<A> ::= <T> 'id' <A> | <T> 'id' ;
<T> ::= 'nat' | 'bool' ;
<C> ::= <B> '?' <E> ':' <C> | <E> ;
<I> ::= <E> <I> | <E> ;
<E> ::= '(' 'id' <I> ')' | 'lit' '+' <E> | 'lit' ;
<B> ::= <E> <R> <E> '&' <B> | <E> <R> <E> ;
<R> ::= '<' | '=' ;
