<start> ::= <S> ;
<S> ::= <F> ';' <S> | <C> ;
<F> ::= 'fun' <id> <A> '->' <C> ;
<A> ::= <T> <id> <A> | <T> 'id' ;
<T> ::= 'nat' | 'bool' ;
<C> ::= <B> '?' <E> ':' <C> | <E> ;
<I> ::= <E> <I> | <E> ;
<E> ::= '(' <id> <I> ')' | <lit> '+' <E> | <lit> ;
<B> ::= <E> <R> <E> '&' <B> | <E> <R> <E> ;
<R> ::= '<' | '=' ;
<id> ::=  'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' |
          'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z' |
          'A' | 'B' | 'C' | 'D' | 'E' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' |
          'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z' ;
<lit> ::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | 'T' | 'F' ;
