permissions:
  contents: read
on:
  push:
    branches: [ master ]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: CI
jobs:

  test:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / clang / test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15.0"
          env: true
      - name: Clean up printf
        run: |
          sed -i '/\bprintf\b/ { N; s/\bprintf\b[^(]*([^)]*)[^;]*;// }' *.c
          sed -i '/\bprintf\b/ { N; s/\bprintf\b[^(]*([^)]*)[^;]*;// }' **/*.c
      - name: Run the tests
        run: make test
        env:
          SANITIZER: 1
          CFLAGS: -O3 -g

  rusty-test:
    runs-on: ubuntu-latest
    name: ubuntu / ${{ matrix.toolchain }} / test
    strategy:
      matrix:
        toolchain: [ stable ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
        working-directory: compiler-testsuite
      - name: cargo test --locked
        run: cargo test --locked --all-features --all-targets
        working-directory: compiler-testsuite

  codecov:
    runs-on: ubuntu-latest
    name: Codecov Report
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install lcov
        working-directory: /tmp
        run: |
          wget  https://github.com/linux-test-project/lcov/releases/download/v2.0/lcov-2.0.tar.gz
          tar -xvf lcov-2.0.tar.gz
          cd lcov-2.0 && sudo make install
      - name: Install lcov deps
        uses: perl-actions/install-with-cpanm@stable
        with:
          install: |
            Capture::Tiny
            DateTime
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          env: true
          version: "15.0"
      - name: Clean up printf
        run: |
          sed -i '/\bprintf\b/ { N; s/\bprintf\b[^(]*([^)]*)[^;]*;// }' *.c
          sed -i '/\bprintf\b/ { N; s/\bprintf\b[^(]*([^)]*)[^;]*;// }' **/*.c
      - name: Get Codecov Report
        run: make codecov
        env:
          CODECOV: 1
      - name: Upload to coveralls
        uses: coverallsapp/github-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.lcov
          compare-ref: origin/master

  typos:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
        with:
          files: .
