permissions:
  contents: read
on:
  push:
    branches: [ master ]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: CI
jobs:

  test:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / clang / test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15.0"
      - name: Run the tests
        run: make test
        env:
          SANITIZER: 1
          DEBUG: 1

  codecov:
    runs-on: ubuntu-latest
    name: Codecov Report
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15.0"
      - name: Install lcov
        run: sudo apt-get -y install lcov
      - name: Check Installation
        run: which llvm-cov
      - name: Get Codecov Report
        run: make codecov
        env:
          CODECOV: 1
          DEBUG: 1
          CC: gcc
      - name: Check Codecov Report
        run: cat coverage.info

  typos:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
        with:
          files: .
